
author: 
  name: K. Bodie Weedop

url: "https://bweedop.github.io"
<<<<<<< HEAD
baseurl: "/jekyll-science"
=======
baseurl: "jekyll-science"
>>>>>>> a97d475a25669f0b6a7cba26749694b673a1f9ae

title: Lab Notebook

logo: half.png

googlefonts: Roboto

text-color: #000000
top-navbar-color: #F5F5F5
top-navbar-link-color: #000000
footer-color: #000000
footer-link-color: #FFFFFF

sass:
  sass_dir: _sass

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
